//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mayaModel", "bitacora_fk", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maya.usuarios), "bitacora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.bitacora), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "mp_tejedora_fk", "materia_prima", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maya.materia_prima), "mp_tejedora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.mp_tejedora), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "mp_tejedora_fk2", "tejedora", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maya.tejedora), "mp_tejedora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.mp_tejedora), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "mp_tejedora_fk3", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Maya.usuarios), "mp_tejedora", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.mp_tejedora), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "productos_fk", "punto_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Maya.punto_venta), "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.productos), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "productos_fk2", "tipo_producto", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maya.tipo_producto), "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.productos), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "productos_fk3", "tejedora", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maya.tejedora), "productos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.productos), true)]
[assembly: EdmRelationshipAttribute("mayaModel", "usuarios_fk", "rol", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Maya.rol), "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Maya.usuarios), true)]

#endregion

namespace Maya
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mayaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mayaEntities object using the connection string found in the 'mayaEntities' section of the application configuration file.
        /// </summary>
        public mayaEntities() : base("name=mayaEntities", "mayaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mayaEntities object.
        /// </summary>
        public mayaEntities(string connectionString) : base(connectionString, "mayaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mayaEntities object.
        /// </summary>
        public mayaEntities(EntityConnection connection) : base(connection, "mayaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<bitacora> bitacora
        {
            get
            {
                if ((_bitacora == null))
                {
                    _bitacora = base.CreateObjectSet<bitacora>("bitacora");
                }
                return _bitacora;
            }
        }
        private ObjectSet<bitacora> _bitacora;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<gastos> gastos
        {
            get
            {
                if ((_gastos == null))
                {
                    _gastos = base.CreateObjectSet<gastos>("gastos");
                }
                return _gastos;
            }
        }
        private ObjectSet<gastos> _gastos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<materia_prima> materia_prima
        {
            get
            {
                if ((_materia_prima == null))
                {
                    _materia_prima = base.CreateObjectSet<materia_prima>("materia_prima");
                }
                return _materia_prima;
            }
        }
        private ObjectSet<materia_prima> _materia_prima;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mp_tejedora> mp_tejedora
        {
            get
            {
                if ((_mp_tejedora == null))
                {
                    _mp_tejedora = base.CreateObjectSet<mp_tejedora>("mp_tejedora");
                }
                return _mp_tejedora;
            }
        }
        private ObjectSet<mp_tejedora> _mp_tejedora;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<productos> productos
        {
            get
            {
                if ((_productos == null))
                {
                    _productos = base.CreateObjectSet<productos>("productos");
                }
                return _productos;
            }
        }
        private ObjectSet<productos> _productos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<punto_venta> punto_venta
        {
            get
            {
                if ((_punto_venta == null))
                {
                    _punto_venta = base.CreateObjectSet<punto_venta>("punto_venta");
                }
                return _punto_venta;
            }
        }
        private ObjectSet<punto_venta> _punto_venta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rol> rol
        {
            get
            {
                if ((_rol == null))
                {
                    _rol = base.CreateObjectSet<rol>("rol");
                }
                return _rol;
            }
        }
        private ObjectSet<rol> _rol;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tejedora> tejedora
        {
            get
            {
                if ((_tejedora == null))
                {
                    _tejedora = base.CreateObjectSet<tejedora>("tejedora");
                }
                return _tejedora;
            }
        }
        private ObjectSet<tejedora> _tejedora;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tipo_producto> tipo_producto
        {
            get
            {
                if ((_tipo_producto == null))
                {
                    _tipo_producto = base.CreateObjectSet<tipo_producto>("tipo_producto");
                }
                return _tipo_producto;
            }
        }
        private ObjectSet<tipo_producto> _tipo_producto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the bitacora EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobitacora(bitacora bitacora)
        {
            base.AddObject("bitacora", bitacora);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the gastos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogastos(gastos gastos)
        {
            base.AddObject("gastos", gastos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the materia_prima EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomateria_prima(materia_prima materia_prima)
        {
            base.AddObject("materia_prima", materia_prima);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mp_tejedora EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomp_tejedora(mp_tejedora mp_tejedora)
        {
            base.AddObject("mp_tejedora", mp_tejedora);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the productos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproductos(productos productos)
        {
            base.AddObject("productos", productos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the punto_venta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopunto_venta(punto_venta punto_venta)
        {
            base.AddObject("punto_venta", punto_venta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rol EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorol(rol rol)
        {
            base.AddObject("rol", rol);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tejedora EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotejedora(tejedora tejedora)
        {
            base.AddObject("tejedora", tejedora);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tipo_producto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotipo_producto(tipo_producto tipo_producto)
        {
            base.AddObject("tipo_producto", tipo_producto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="bitacora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class bitacora : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new bitacora object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="id_usuario">Initial value of the id_usuario property.</param>
        public static bitacora Createbitacora(global::System.Int32 id, global::System.String descripcion, global::System.Int32 id_usuario)
        {
            bitacora bitacora = new bitacora();
            bitacora.id = id;
            bitacora.descripcion = descripcion;
            bitacora.id_usuario = id_usuario;
            return bitacora;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha;
        partial void OnfechaChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "bitacora_fk", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("mayaModel.bitacora_fk", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("mayaModel.bitacora_fk", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("mayaModel.bitacora_fk", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("mayaModel.bitacora_fk", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="gastos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class gastos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new gastos object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="fecha">Initial value of the fecha property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        public static gastos Creategastos(global::System.Int32 id, global::System.DateTime fecha, global::System.String descripcion, global::System.Decimal valor)
        {
            gastos gastos = new gastos();
            gastos.id = id;
            gastos.fecha = fecha;
            gastos.descripcion = descripcion;
            gastos.valor = valor;
            return gastos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.Decimal _valor;
        partial void OnvalorChanging(global::System.Decimal value);
        partial void OnvalorChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="materia_prima")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class materia_prima : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new materia_prima object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static materia_prima Createmateria_prima(global::System.Int32 id)
        {
            materia_prima materia_prima = new materia_prima();
            materia_prima.id = id;
            return materia_prima;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private Nullable<global::System.Decimal> _cantidad;
        partial void OncantidadChanging(Nullable<global::System.Decimal> value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "mp_tejedora_fk", "mp_tejedora")]
        public EntityCollection<mp_tejedora> mp_tejedora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mp_tejedora>("mayaModel.mp_tejedora_fk", "mp_tejedora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mp_tejedora>("mayaModel.mp_tejedora_fk", "mp_tejedora", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="mp_tejedora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mp_tejedora : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mp_tejedora object.
        /// </summary>
        /// <param name="id_mp">Initial value of the id_mp property.</param>
        /// <param name="id_tejedora">Initial value of the id_tejedora property.</param>
        /// <param name="cantidad">Initial value of the cantidad property.</param>
        /// <param name="fehca">Initial value of the fehca property.</param>
        public static mp_tejedora Createmp_tejedora(global::System.Int32 id_mp, global::System.Int32 id_tejedora, global::System.Decimal cantidad, global::System.DateTime fehca)
        {
            mp_tejedora mp_tejedora = new mp_tejedora();
            mp_tejedora.id_mp = id_mp;
            mp_tejedora.id_tejedora = id_tejedora;
            mp_tejedora.cantidad = cantidad;
            mp_tejedora.fehca = fehca;
            return mp_tejedora;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_mp
        {
            get
            {
                return _id_mp;
            }
            set
            {
                if (_id_mp != value)
                {
                    Onid_mpChanging(value);
                    ReportPropertyChanging("id_mp");
                    _id_mp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_mp");
                    Onid_mpChanged();
                }
            }
        }
        private global::System.Int32 _id_mp;
        partial void Onid_mpChanging(global::System.Int32 value);
        partial void Onid_mpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tejedora
        {
            get
            {
                return _id_tejedora;
            }
            set
            {
                if (_id_tejedora != value)
                {
                    Onid_tejedoraChanging(value);
                    ReportPropertyChanging("id_tejedora");
                    _id_tejedora = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tejedora");
                    Onid_tejedoraChanged();
                }
            }
        }
        private global::System.Int32 _id_tejedora;
        partial void Onid_tejedoraChanging(global::System.Int32 value);
        partial void Onid_tejedoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Decimal _cantidad;
        partial void OncantidadChanging(global::System.Decimal value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fehca
        {
            get
            {
                return _fehca;
            }
            set
            {
                OnfehcaChanging(value);
                ReportPropertyChanging("fehca");
                _fehca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fehca");
                OnfehcaChanged();
            }
        }
        private global::System.DateTime _fehca;
        partial void OnfehcaChanging(global::System.DateTime value);
        partial void OnfehcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private Nullable<global::System.Int32> _id_usuario;
        partial void Onid_usuarioChanging(Nullable<global::System.Int32> value);
        partial void Onid_usuarioChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "mp_tejedora_fk", "materia_prima")]
        public materia_prima materia_prima
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<materia_prima>("mayaModel.mp_tejedora_fk", "materia_prima").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<materia_prima>("mayaModel.mp_tejedora_fk", "materia_prima").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<materia_prima> materia_primaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<materia_prima>("mayaModel.mp_tejedora_fk", "materia_prima");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<materia_prima>("mayaModel.mp_tejedora_fk", "materia_prima", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "mp_tejedora_fk2", "tejedora")]
        public tejedora tejedora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tejedora>("mayaModel.mp_tejedora_fk2", "tejedora").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tejedora>("mayaModel.mp_tejedora_fk2", "tejedora").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tejedora> tejedoraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tejedora>("mayaModel.mp_tejedora_fk2", "tejedora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tejedora>("mayaModel.mp_tejedora_fk2", "tejedora", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "mp_tejedora_fk3", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("mayaModel.mp_tejedora_fk3", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("mayaModel.mp_tejedora_fk3", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("mayaModel.mp_tejedora_fk3", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("mayaModel.mp_tejedora_fk3", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="productos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class productos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new productos object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="id_tipo_producto">Initial value of the id_tipo_producto property.</param>
        /// <param name="anno">Initial value of the anno property.</param>
        /// <param name="id_tejedora">Initial value of the id_tejedora property.</param>
        /// <param name="numero_producto">Initial value of the numero_producto property.</param>
        /// <param name="descripcion">Initial value of the descripcion property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        /// <param name="fecha_entrada">Initial value of the fecha_entrada property.</param>
        public static productos Createproductos(global::System.String id, global::System.Int32 id_tipo_producto, global::System.Int32 anno, global::System.Int32 id_tejedora, global::System.Int32 numero_producto, global::System.String descripcion, global::System.Decimal valor, global::System.DateTime fecha_entrada)
        {
            productos productos = new productos();
            productos.id = id;
            productos.id_tipo_producto = id_tipo_producto;
            productos.anno = anno;
            productos.id_tejedora = id_tejedora;
            productos.numero_producto = numero_producto;
            productos.descripcion = descripcion;
            productos.valor = valor;
            productos.fecha_entrada = fecha_entrada;
            return productos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tipo_producto
        {
            get
            {
                return _id_tipo_producto;
            }
            set
            {
                if (_id_tipo_producto != value)
                {
                    Onid_tipo_productoChanging(value);
                    ReportPropertyChanging("id_tipo_producto");
                    _id_tipo_producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tipo_producto");
                    Onid_tipo_productoChanged();
                }
            }
        }
        private global::System.Int32 _id_tipo_producto;
        partial void Onid_tipo_productoChanging(global::System.Int32 value);
        partial void Onid_tipo_productoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 anno
        {
            get
            {
                return _anno;
            }
            set
            {
                if (_anno != value)
                {
                    OnannoChanging(value);
                    ReportPropertyChanging("anno");
                    _anno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("anno");
                    OnannoChanged();
                }
            }
        }
        private global::System.Int32 _anno;
        partial void OnannoChanging(global::System.Int32 value);
        partial void OnannoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tejedora
        {
            get
            {
                return _id_tejedora;
            }
            set
            {
                if (_id_tejedora != value)
                {
                    Onid_tejedoraChanging(value);
                    ReportPropertyChanging("id_tejedora");
                    _id_tejedora = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tejedora");
                    Onid_tejedoraChanged();
                }
            }
        }
        private global::System.Int32 _id_tejedora;
        partial void Onid_tejedoraChanging(global::System.Int32 value);
        partial void Onid_tejedoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero_producto
        {
            get
            {
                return _numero_producto;
            }
            set
            {
                if (_numero_producto != value)
                {
                    Onnumero_productoChanging(value);
                    ReportPropertyChanging("numero_producto");
                    _numero_producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numero_producto");
                    Onnumero_productoChanged();
                }
            }
        }
        private global::System.Int32 _numero_producto;
        partial void Onnumero_productoChanging(global::System.Int32 value);
        partial void Onnumero_productoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.Decimal _valor;
        partial void OnvalorChanging(global::System.Decimal value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private Nullable<global::System.Decimal> _precio;
        partial void OnprecioChanging(Nullable<global::System.Decimal> value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_entrada
        {
            get
            {
                return _fecha_entrada;
            }
            set
            {
                Onfecha_entradaChanging(value);
                ReportPropertyChanging("fecha_entrada");
                _fecha_entrada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_entrada");
                Onfecha_entradaChanged();
            }
        }
        private global::System.DateTime _fecha_entrada;
        partial void Onfecha_entradaChanging(global::System.DateTime value);
        partial void Onfecha_entradaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_salida
        {
            get
            {
                return _fecha_salida;
            }
            set
            {
                Onfecha_salidaChanging(value);
                ReportPropertyChanging("fecha_salida");
                _fecha_salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_salida");
                Onfecha_salidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_salida;
        partial void Onfecha_salidaChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_salidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_devolucion
        {
            get
            {
                return _fecha_devolucion;
            }
            set
            {
                Onfecha_devolucionChanging(value);
                ReportPropertyChanging("fecha_devolucion");
                _fecha_devolucion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_devolucion");
                Onfecha_devolucionChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_devolucion;
        partial void Onfecha_devolucionChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_devolucionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fecha_venta
        {
            get
            {
                return _fecha_venta;
            }
            set
            {
                Onfecha_ventaChanging(value);
                ReportPropertyChanging("fecha_venta");
                _fecha_venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_venta");
                Onfecha_ventaChanged();
            }
        }
        private Nullable<global::System.DateTime> _fecha_venta;
        partial void Onfecha_ventaChanging(Nullable<global::System.DateTime> value);
        partial void Onfecha_ventaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_punto_venta
        {
            get
            {
                return _id_punto_venta;
            }
            set
            {
                Onid_punto_ventaChanging(value);
                ReportPropertyChanging("id_punto_venta");
                _id_punto_venta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_punto_venta");
                Onid_punto_ventaChanged();
            }
        }
        private Nullable<global::System.Int32> _id_punto_venta;
        partial void Onid_punto_ventaChanging(Nullable<global::System.Int32> value);
        partial void Onid_punto_ventaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vendido
        {
            get
            {
                return _vendido;
            }
            set
            {
                OnvendidoChanging(value);
                ReportPropertyChanging("vendido");
                _vendido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vendido");
                OnvendidoChanged();
            }
        }
        private Nullable<global::System.Int32> _vendido;
        partial void OnvendidoChanging(Nullable<global::System.Int32> value);
        partial void OnvendidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tejedora_anterior
        {
            get
            {
                return _tejedora_anterior;
            }
            set
            {
                Ontejedora_anteriorChanging(value);
                ReportPropertyChanging("tejedora_anterior");
                _tejedora_anterior = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tejedora_anterior");
                Ontejedora_anteriorChanged();
            }
        }
        private global::System.String _tejedora_anterior;
        partial void Ontejedora_anteriorChanging(global::System.String value);
        partial void Ontejedora_anteriorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "productos_fk", "punto_venta")]
        public punto_venta punto_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<punto_venta>("mayaModel.productos_fk", "punto_venta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<punto_venta>("mayaModel.productos_fk", "punto_venta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<punto_venta> punto_ventaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<punto_venta>("mayaModel.productos_fk", "punto_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<punto_venta>("mayaModel.productos_fk", "punto_venta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "productos_fk2", "tipo_producto")]
        public tipo_producto tipo_producto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_producto>("mayaModel.productos_fk2", "tipo_producto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_producto>("mayaModel.productos_fk2", "tipo_producto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipo_producto> tipo_productoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipo_producto>("mayaModel.productos_fk2", "tipo_producto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipo_producto>("mayaModel.productos_fk2", "tipo_producto", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "productos_fk3", "tejedora")]
        public tejedora tejedora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tejedora>("mayaModel.productos_fk3", "tejedora").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tejedora>("mayaModel.productos_fk3", "tejedora").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tejedora> tejedoraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tejedora>("mayaModel.productos_fk3", "tejedora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tejedora>("mayaModel.productos_fk3", "tejedora", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="punto_venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class punto_venta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new punto_venta object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        public static punto_venta Createpunto_venta(global::System.Int32 id, global::System.String valor)
        {
            punto_venta punto_venta = new punto_venta();
            punto_venta.id = id;
            punto_venta.valor = valor;
            return punto_venta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.String _valor;
        partial void OnvalorChanging(global::System.String value);
        partial void OnvalorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "productos_fk", "productos")]
        public EntityCollection<productos> productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<productos>("mayaModel.productos_fk", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<productos>("mayaModel.productos_fk", "productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="rol")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rol : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rol object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        public static rol Createrol(global::System.Int32 id, global::System.String valor)
        {
            rol rol = new rol();
            rol.id = id;
            rol.valor = valor;
            return rol;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.String _valor;
        partial void OnvalorChanging(global::System.String value);
        partial void OnvalorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "usuarios_fk", "usuarios")]
        public EntityCollection<usuarios> usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<usuarios>("mayaModel.usuarios_fk", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<usuarios>("mayaModel.usuarios_fk", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="tejedora")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tejedora : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tejedora object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="apellidos">Initial value of the apellidos property.</param>
        public static tejedora Createtejedora(global::System.Int32 id, global::System.String nombre, global::System.String apellidos)
        {
            tejedora tejedora = new tejedora();
            tejedora.id = id;
            tejedora.nombre = nombre;
            tejedora.apellidos = apellidos;
            return tejedora;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellidos
        {
            get
            {
                return _apellidos;
            }
            set
            {
                OnapellidosChanging(value);
                ReportPropertyChanging("apellidos");
                _apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellidos");
                OnapellidosChanged();
            }
        }
        private global::System.String _apellidos;
        partial void OnapellidosChanging(global::System.String value);
        partial void OnapellidosChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "mp_tejedora_fk2", "mp_tejedora")]
        public EntityCollection<mp_tejedora> mp_tejedora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mp_tejedora>("mayaModel.mp_tejedora_fk2", "mp_tejedora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mp_tejedora>("mayaModel.mp_tejedora_fk2", "mp_tejedora", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "productos_fk3", "productos")]
        public EntityCollection<productos> productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<productos>("mayaModel.productos_fk3", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<productos>("mayaModel.productos_fk3", "productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="tipo_producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipo_producto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tipo_producto object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tipo_producto Createtipo_producto(global::System.Int32 id)
        {
            tipo_producto tipo_producto = new tipo_producto();
            tipo_producto.id = id;
            return tipo_producto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.String _valor;
        partial void OnvalorChanging(global::System.String value);
        partial void OnvalorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "productos_fk2", "productos")]
        public EntityCollection<productos> productos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<productos>("mayaModel.productos_fk2", "productos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<productos>("mayaModel.productos_fk2", "productos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mayaModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuarios object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="apellidos">Initial value of the apellidos property.</param>
        /// <param name="usuario">Initial value of the usuario property.</param>
        /// <param name="pass">Initial value of the pass property.</param>
        /// <param name="id_rol">Initial value of the id_rol property.</param>
        public static usuarios Createusuarios(global::System.Int32 id, global::System.String nombre, global::System.String apellidos, global::System.String usuario, global::System.String pass, global::System.Int32 id_rol)
        {
            usuarios usuarios = new usuarios();
            usuarios.id = id;
            usuarios.nombre = nombre;
            usuarios.apellidos = apellidos;
            usuarios.usuario = usuario;
            usuarios.pass = pass;
            usuarios.id_rol = id_rol;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellidos
        {
            get
            {
                return _apellidos;
            }
            set
            {
                OnapellidosChanging(value);
                ReportPropertyChanging("apellidos");
                _apellidos = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellidos");
                OnapellidosChanged();
            }
        }
        private global::System.String _apellidos;
        partial void OnapellidosChanging(global::System.String value);
        partial void OnapellidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_rol
        {
            get
            {
                return _id_rol;
            }
            set
            {
                Onid_rolChanging(value);
                ReportPropertyChanging("id_rol");
                _id_rol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_rol");
                Onid_rolChanged();
            }
        }
        private global::System.Int32 _id_rol;
        partial void Onid_rolChanging(global::System.Int32 value);
        partial void Onid_rolChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "bitacora_fk", "bitacora")]
        public EntityCollection<bitacora> bitacora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<bitacora>("mayaModel.bitacora_fk", "bitacora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<bitacora>("mayaModel.bitacora_fk", "bitacora", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "mp_tejedora_fk3", "mp_tejedora")]
        public EntityCollection<mp_tejedora> mp_tejedora
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mp_tejedora>("mayaModel.mp_tejedora_fk3", "mp_tejedora");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mp_tejedora>("mayaModel.mp_tejedora_fk3", "mp_tejedora", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mayaModel", "usuarios_fk", "rol")]
        public rol rol
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rol>("mayaModel.usuarios_fk", "rol").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rol>("mayaModel.usuarios_fk", "rol").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<rol> rolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<rol>("mayaModel.usuarios_fk", "rol");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<rol>("mayaModel.usuarios_fk", "rol", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
